# Generated by Django 4.2.16 on 2024-10-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_image_url_product_stl_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
