# Generated by Django 4.2.16 on 2024-10-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_seller_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('stl_url', models.URLField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('material', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('En proceso', 'En proceso'), ('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=255)),
                ('sellerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seller')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
