# Generated by Django 4.2.16 on 2024-10-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_printrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printrequest',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada'), ('Cotizada', 'Cotizada'), ('Cancelada', 'Cancelada'), ('En proceso', 'En proceso'), ('Realizada', 'Realizada')], default='Pendiente', max_length=255),
        ),
    ]
