# Generated by Django 4.2.16 on 2024-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_printrequest_price_alter_printrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='printrequest',
            name='material',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
