# Generated by Django 4.2.16 on 2024-10-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.AddField(
            model_name='seller',
            name='mp_mail',
            field=models.EmailField(default='mercado_pago@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'unique_together': {('product', 'material')},
            },
        ),
    ]
