# Generated by Django 4.2.16 on 2024-10-07 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_product_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequestImage',
            fields=[
                ('image_url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('material', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada'), ('Cotizada', 'Cotizada'), ('Cancelada', 'Cancelada'), ('En proceso', 'En proceso'), ('Realizada', 'Realizada')], default='Pendiente', max_length=255)),
                ('design_images', models.ManyToManyField(to='api.designrequestimage')),
                ('sellerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seller')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
