# Generated by Django 4.2.16 on 2024-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_designrequestimage_designrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='materials',
            field=models.ManyToManyField(null=True, related_name='sellers', to='api.material'),
        ),
    ]
