# Generated by Django 4.2.16 on 2024-10-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_seller_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada'), ('Cotizada', 'Cotizada'), ('Cancelada', 'Cancelada'), ('En proceso', 'En proceso'), ('Realizada', 'Realizada'), ('Aceptada', 'Aceptada')], default='Pendiente', max_length=255),
        ),
    ]
