# Generated by Django 5.1.1 on 2024-10-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_designrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
