# Generated by Django 4.2.16 on 2024-10-16 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_alter_designrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintReverseAuction',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('material', models.CharField(max_length=255, null=True)),
                ('stl_file', models.URLField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrintReverseAuctionResponse',
            fields=[
                ('responseID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=255)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.printreverseauction')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
            ],
        ),
        migrations.AddField(
            model_name='printreverseauction',
            name='accepted_response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_auction', to='api.printreverseauctionresponse'),
        ),
        migrations.AddField(
            model_name='printreverseauction',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
