# Generated by Django 4.2.16 on 2024-10-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_printreverseauction_printreverseauctionresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printreverseauction',
            name='stl_file',
        ),
    ]
