# Generated by Django 5.1.1 on 2024-10-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_designreverseauction_designreverseauctionresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
