# Generated by Django 5.1.3 on 2024-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_printrequest_status_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='review_sum',
            field=models.IntegerField(default=0),
        ),
    ]
