# Generated by Django 5.1.1 on 2024-12-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_order_productcode_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='mp_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
