# Generated by Django 5.1.1 on 2024-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_seller_mp_access_token_seller_mp_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
