# Generated by Django 4.2.16 on 2024-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_seller_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='review_sum',
            field=models.IntegerField(default=0),
        ),
    ]
