# Generated by Django 5.1.1 on 2024-12-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='designreverseauction',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printreverseauction',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
