# Generated by Django 5.1.1 on 2024-12-16 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sellerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seller'),
        ),
    ]
